import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";

type NavItem = { label: string; icon: string; badge?: string };

const navigation: { group: string; items: NavItem[] }[] = [
  { group: "Overview", items: [{ label: "Dashboard", icon: "⌘" }, { label: "Dynamic information", icon: "⌗" }] },
  { group: "Academics", items: [{ label: "Students", icon: "♙" }, { label: "Family management", icon: "♧" }, { label: "Exams & results", icon: "✦" }, { label: "Timetable", icon: "▦" }, { label: "ID cards", icon: "▣" }] },
  { group: "Finance", items: [{ label: "Fees", icon: "₹" }, { label: "Late fees list", icon: "!" }, { label: "Monthly fee & salary status", icon: "◷" }, { label: "Staff", icon: "♜" }, { label: "Expenses", icon: "↗" }, { label: "Donations", icon: "♡" }, { label: "Transport", icon: "▱" }, { label: "Financial analytics", icon: "⌁" }] },
  { group: "Administration", items: [{ label: "Alerts", icon: "◉", badge: "12" }, { label: "Automation", icon: "⊙" }, { label: "Reports", icon: "▤" }, { label: "Activity logs", icon: "◷" }, { label: "Developer info", icon: "ⓘ" }, { label: "Trash bin", icon: "♲" }, { label: "Settings", icon: "⚙" }, { label: "Backup", icon: "◌" }, { label: "Historical records", icon: "◫" }] },
];

const stats = [
  ["1,248", "Total students", "+32 this session", "teal"], ["128", "Total staff", "4 joining this month", "purple"],
  ["Rs. 842k", "Fees collected", "86% of September", "green"], ["Rs. 131k", "Pending fees", "74 accounts overdue", "amber"],
  ["Rs. 384k", "Salaries paid", "September payroll", "slate"], ["Rs. 96.4k", "Total expenses", "+8.2% vs August", "red"],
  ["Rs. 48k", "Donations received", "3 active donors", "violet"], ["Rs. 279k", "Net balance", "Positive this month", "green"],
];

const students = [
  ["01", "ADM-2401", "Ayesha Khan", "Muhammad Khan", "9-A", "Female", "0301 245 8092", "Rs. 9,500", "Active"],
  ["02", "ADM-2402", "Hamza Ali", "Zafar Ali", "9-A", "Male", "0333 612 5901", "Rs. 10,000", "Active"],
  ["03", "ADM-2388", "Fatima Noor", "Irfan Noor", "9-B", "Female", "0308 772 1045", "Rs. 9,500", "Pending"],
  ["04", "ADM-2392", "Omar Shah", "Faisal Shah", "8-C", "Male", "0314 899 2340", "Rs. 11,500", "Active"],
  ["05", "ADM-2408", "Zoya Ahmed", "Nadeem Ahmed", "7-B", "Female", "0300 401 7762", "Rs. 9,000", "Active"],
];

const actions = ["Add student", "Add fee payment", "Pay salary", "Add expense", "Generate report", "Create backup"];

function Logo() { return <div className="logo-mark"><span>✦</span></div>; }
function IconButton({ children, label, onClick }: { children: ReactNode; label: string; onClick?: () => void }) { return <button onClick={onClick} className="icon-button" aria-label={label}>{children}</button>; }

export default function App() {
  const [signedIn, setSignedIn] = useState(false);
  const [page, setPage] = useState("Dashboard");
  const [dark, setDark] = useState(false);
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<string[]>([]);
  const [toast, setToast] = useState("");
  const [modal, setModal] = useState<"Student" | "Fee payment" | null>(null);
  const [liveTime, setLiveTime] = useState(new Date());
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  useEffect(() => { const i = setInterval(() => setLiveTime(new Date()), 1000); return () => clearInterval(i); }, []);
  useEffect(() => { if (!toast) return; const t = setTimeout(() => setToast(""), 2400); return () => clearTimeout(t); }, [toast]);
  const filteredStudents = useMemo(() => students.filter(s => s.join(" ").toLowerCase().includes(search.toLowerCase())), [search]);
  const navigate = (label: string) => { setPage(label); setSidebarOpen(false); setSearch(""); };
  const tablePage = page === "Students" || page === "Fees" || page === "Staff" || page === "Expenses" || page === "Donations" || page === "Late fees list";

  if (!signedIn) return <Login onSuccess={() => setSignedIn(true)} />;

  return <div className={`${dark ? "app dark" : "app"} ${sidebarCollapsed ? "sidebar-collapsed" : ""}`}>
    <aside className={`${sidebarOpen ? "sidebar sidebar-open" : "sidebar"} ${sidebarCollapsed ? "sidebar-mini" : ""}`}>
      <div className="brand"><Logo /><div className="brand-name"><strong>Northstar</strong><small>PUBLIC SCHOOL</small></div><button className="collapse-nav" onClick={() => setSidebarCollapsed(!sidebarCollapsed)} aria-label={sidebarCollapsed ? "Expand navigation" : "Collapse navigation"}>{sidebarCollapsed ? "›" : "‹"}</button><button className="close-nav" onClick={() => setSidebarOpen(false)} aria-label="Close navigation">×</button></div>
      <div className="session-chip"><span>2025–26</span><b>⌄</b></div>
      <nav>{navigation.map(group => <section key={group.group}><p className="nav-heading">{group.group}</p>{group.items.map(item => <button key={item.label} onClick={() => navigate(item.label)} className={page === item.label ? "nav-item active" : "nav-item"}><i>{item.icon}</i><span>{item.label}</span>{item.badge && <em>{item.badge}</em>}</button>)}</section>)}</nav>
      <div className="sidebar-foot"><div className="backup-dot">● <span>Backup secure</span><small>Today, 04:30</small></div><button className="profile-card" onClick={() => setToast("Profile settings opened")}><div className="avatar">SA</div><span><b>Sarah Ahmed</b><small>Administrator</small></span><i>•••</i></button></div>
    </aside>
    <main className="workspace">
      <header className="topbar"><button className="menu-button" onClick={() => setSidebarOpen(true)}>☰</button><div className="breadcrumb"><span>Northstar /</span> <b>{page}</b></div><div className="top-actions"><span className="clock">{liveTime.toLocaleDateString("en-US", { month: "short", day: "numeric" })} · {liveTime.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" })}</span><label className="search"><span>⌕</span><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search students, fees, records…"/><kbd>⌘ K</kbd></label><IconButton label="Notifications" onClick={() => setToast("12 new notifications")}>♧<mark></mark></IconButton><button className="theme-toggle" onClick={() => setDark(!dark)}><span className={dark ? "" : "on"}>☼</span><span className={dark ? "on" : ""}>◐</span></button><button className="logout" onClick={() => setSignedIn(false)}>↪ <span>Log out</span></button></div></header>
      <div className="content">{page === "Dashboard" ? <Dashboard go={navigate} toast={setToast} /> : page === "Settings" ? <SettingsPage toast={setToast} /> : tablePage ? <ManagementPage page={page} search={search} rows={filteredStudents} selected={selected} setSelected={setSelected} toast={setToast} openModal={setModal} /> : <ModulePage page={page} toast={setToast} />}</div>
    </main><footer className="system-status"><span><i></i> API ready</span><span>DB <b>Connected</b></span><span>Worker <b>Idle</b></span><span className="status-grow">CPU 14% · RAM 286 MB · developer edition</span><span>Northstar Web 1.0.0</span></footer>
    {sidebarOpen && <button className="scrim" onClick={() => setSidebarOpen(false)} aria-label="Close menu"/>}
    {toast && <div className="toast"><span>✓</span>{toast}</div>}
    {modal && <RecordModal kind={modal} close={() => setModal(null)} notify={(message) => { setModal(null); setToast(message); }} />}
  </div>;
}

function Login({ onSuccess }: { onSuccess: () => void }) {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const login = (event: FormEvent) => {
    event.preventDefault();
    if (!username || !password) { setError("Enter your username and password to continue."); return; }
    setError(""); setLoading(true);
    setTimeout(() => { setLoading(false); onSuccess(); }, 900);
  };
  return <main className="login-page"><div className="login-mesh one"></div><div className="login-mesh two"></div><section className="login-story"><div className="login-brand"><Logo /><span><b>Northstar</b><small>PUBLIC SCHOOL</small></span></div><div className="story-copy"><p className="eyebrow">ADMINISTRATION PORTAL</p><h1>School, in<br/><em>good order.</em></h1><p>Northstar’s secure workspace connects your classrooms, finances, families, and daily operations.</p></div><div className="story-stats"><span><b>1,248</b> active students</span><span><b>12</b> modules, one view</span><span><b>99.9%</b> records protected</span></div></section><section className="login-panel"><form onSubmit={login}><div className="login-heading"><p className="eyebrow">WELCOME BACK</p><h2>Sign in to your workspace</h2><p>Use the account provided by your school administrator.</p></div><label className="field-label">USERNAME<input value={username} onChange={e => setUsername(e.target.value)} autoComplete="username" placeholder="e.g. sarah.ahmed" /></label><label className="field-label">PASSWORD<span className="password-field"><input value={password} onChange={e => setPassword(e.target.value)} type={showPassword ? "text" : "password"} autoComplete="current-password" placeholder="Enter your password" /><button type="button" onClick={() => setShowPassword(!showPassword)}>{showPassword ? "Hide" : "Show"}</button></span></label>{error && <p className="login-error">! {error}</p>}<button className="login-submit" disabled={loading}>{loading ? <><i className="loader"></i> Signing in…</> : <>Sign in <span>→</span></>}</button><div className="login-help"><span>Protected by Northstar Secure</span><button type="button" onClick={() => setError("Please contact the school administrator to reset your password.")}>Need help?</button></div></form><footer>© 2025 Northstar Public School <i>·</i> Private & secure</footer></section></main>;
}

function Dashboard({ go, toast }: { go: (x: string) => void; toast: (x: string) => void }) { return <>
  <section className="page-intro"><div><p className="eyebrow">TUESDAY, SEPTEMBER 16</p><h1>Good morning, Sarah.</h1><p>Here is the pulse of Northstar Public School.</p></div><div className="intro-actions"><button className="subtle-button" onClick={() => toast("Showing all alerts")}>◉ View alerts <b>12</b></button><button className="primary-button" onClick={() => go("Students")}>＋ Add student</button></div></section>
  <section className="metric-grid">{stats.map(([number, label, note, tone]) => <article className={`metric-card ${tone}`} key={label}><p>{label}</p><h2>{number}</h2><small><i>↗</i> {note}</small></article>)}</section>
  <section className="quick-row"><div><p className="section-label">QUICK ACTIONS</p><div className="quick-actions">{actions.map((a, i) => <button key={a} onClick={() => a.includes("student") ? go("Students") : a.includes("fee") ? go("Fees") : toast(`${a} panel opened`)}><i>{["＋","₹","♜","↗","▤","◌"][i]}</i><span>{a}</span></button>)}</div></div><aside className="backup-card"><div className="mini-logo">◌</div><div><p>Last backup</p><b>Today, 04:30 AM</b><small>Encrypted · 428 MB</small></div><button onClick={() => toast("Backup started — you’ll be notified")}>Create</button></aside></section>
  <section className="dashboard-lower"><article className="chart-card income"><div className="card-title"><div><p className="section-label">FINANCIAL OVERVIEW</p><h3>Income & expenses</h3></div><select defaultValue="September"><option>September</option><option>August</option></select></div><div className="legend"><span><i className="dot green-dot"></i>Income <b>Rs. 890k</b></span><span><i className="dot coral-dot"></i>Expenses <b>Rs. 480k</b></span></div><div className="chart-area"><div className="y-labels"><span>1M</span><span>750k</span><span>500k</span><span>250k</span><span>0</span></div><div className="bars">{[[58,39],[70,42],[54,37],[78,48],[66,54],[85,43],[76,51],[89,46],[81,60],[90,48],[76,44],[84,53]].map((b,i)=><div key={i} className="bar-set"><i style={{height:`${b[0]}%`}}></i><i style={{height:`${b[1]}%`}}></i><small>{["O","N","D","J","F","M","A","M","J","J","A","S"][i]}</small></div>)}</div></div></article>
  <article className="chart-card fees"><div className="card-title"><div><p className="section-label">FEE COLLECTION</p><h3>September progress</h3></div><button onClick={() => go("Fees")}>Open fees →</button></div><div className="donut"><div><strong>86%</strong><span>collected</span></div></div><div className="fee-summary"><span><b>Rs. 842k</b> collected</span><span><b>Rs. 131k</b> pending</span></div><div className="progress"><i></i></div></article></section>
  <section className="dashboard-lower bottom"><article className="table-card"><div className="card-title"><div><p className="section-label">NEEDS ATTENTION</p><h3>Recent alerts</h3></div><button onClick={() => go("Alerts")}>View all →</button></div>{[["Overdue fees","74 students have fees overdue by 10+ days","High"],["Payroll pending","September salary awaits approval","Medium"],["Backup verified","Daily encrypted backup completed","Resolved"]].map(a=><div className="alert-row" key={a[0]}><i className={a[2].toLowerCase()}></i><span><b>{a[0]}</b><small>{a[1]}</small></span><em>{a[2]}</em></div>)}</article><article className="table-card activity"><div className="card-title"><div><p className="section-label">LIVE ACTIVITY</p><h3>Today’s ledger</h3></div><button>Open log →</button></div>{[["Fee received", "Ayesha Khan", "+ Rs. 9,500"],["Expense added", "Science laboratory supplies", "− Rs. 12,400"],["Student enrolled", "Mikael Farooq · Grade 4", "09:42"]].map(a=><div className="ledger-row" key={a[0]}><i>◈</i><span><b>{a[0]}</b><small>{a[1]}</small></span><em>{a[2]}</em></div>)}</article></section>
  </> }

function ManagementPage({ page, search, rows, selected, setSelected, toast, openModal }: { page: string; search: string; rows: string[][]; selected: string[]; setSelected: (x: string[]) => void; toast:(x:string)=>void; openModal:(x:"Student"|"Fee payment")=>void }) {
 const isStudents = page === "Students"; const title = page === "Staff" ? "Staff directory" : page === "Late fees list" ? "Late fee & defaulters" : `${page} management`;
 const fields = isStudents ? ["Roll", "Admission no.", "Student", "Guardian", "Class", "Gender", "Phone", "Monthly fee", "Status"] : ["Record", "Name", "Class / role", "Month", "Amount", "Payment method", "Date", "Status", "Actions"];
 const data = isStudents ? rows : students.map((r,i)=>[`${page.slice(0,2).toUpperCase()}-${2100+i}`, r[2], page === "Staff" ? ["Teacher", "Coordinator", "Accountant", "Driver", "Teacher"][i] : r[4], "September 2025", `Rs. ${(9500+i*1200).toLocaleString()}`, i%2 ? "Bank transfer" : "Cash", "16 Sep 2025", i===2 ? "Pending" : "Complete", "•••"]);
 const select = (id: string) => setSelected(selected.includes(id) ? selected.filter(x=>x!==id) : [...selected,id]);
 return <><section className="page-intro compact"><div><p className="eyebrow">{isStudents ? "STUDENT DIRECTORY" : "OPERATIONS / RECORDS"}</p><h1>{title}</h1><p>{isStudents ? "Manage enrollment, profiles and academic records in one place." : "Review records, apply filters, and keep each transaction auditable."}</p></div><div className="intro-actions"><button className="subtle-button" onClick={()=>toast("Export prepared for download")}>⇩ Export</button><button className="primary-button" onClick={()=>isStudents?openModal("Student"):page==="Fees"?openModal("Fee payment"):toast(`New ${page.toLowerCase()} form opened`)}>＋ Add {page === "Staff" ? "staff" : page.slice(0,-1)}</button></div></section>
 <section className="filters"><label className="table-search">⌕ <input value={search} readOnly placeholder={`Search ${page.toLowerCase()}…`} /></label><select><option>All classes</option><option>Grade 9</option><option>Grade 8</option></select><select><option>All statuses</option><option>Active</option><option>Pending</option></select><select><option>2025–26 session</option></select><button onClick={()=>toast("Filters reset")}>↻ Reset</button></section>
 <section className="data-shell"><div className="table-toolbar"><span>{selected.length ? <><b>{selected.length}</b> selected <button onClick={()=>toast("Archive confirmation opened")}>Archive selected</button></> : <><b>{data.length === 5 && search ? data.length : isStudents ? "1,248" : "386"}</b> records <small>• Sorted by latest activity</small></>}</span><div><button onClick={()=>toast("Column controls opened")}>☷ Columns</button><button onClick={()=>toast("Print preview opened")}>▤ Print</button></div></div><div className="table-scroll"><table><thead><tr><th><input aria-label="Select all" type="checkbox" checked={selected.length === data.length} onChange={()=>setSelected(selected.length===data.length?[]:data.map((_,i)=>String(i)))}/></th>{fields.map(x=><th key={x}>{x} {x !== "Actions" && <small>↕</small>}</th>)}</tr></thead><tbody>{data.map((r,i)=><tr key={r[0]}><td><input aria-label={`Select ${r[1]}`} type="checkbox" checked={selected.includes(String(i))} onChange={()=>select(String(i))}/></td>{r.map((c,j)=><td key={j}>{j === 2 && isStudents ? <span className="student-name"><i>{c.split(" ").map(x=>x[0]).join("")}</i><b>{c}</b></span> : j === r.length-1 && !isStudents ? <button className="more" onClick={()=>toast(`Actions opened for ${r[1]}`)}>•••</button> : (c === "Active" || c === "Complete" || c === "Pending") ? <span className={`status ${c.toLowerCase()}`}>{c}</span> : c}</td>)}</tr>)}</tbody></table></div><footer className="pagination"><span>Showing <b>1–{data.length}</b> of <b>{isStudents ? "1,248" : "386"}</b></span><div><button disabled>←</button><button className="current">1</button><button>2</button><button>3</button><button>→</button></div></footer></section></>;
}

function RecordModal({ kind, close, notify }: { kind: "Student" | "Fee payment"; close: () => void; notify: (x: string) => void }) {
  const [notice, setNotice] = useState("");
  const submit = (event: FormEvent) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (kind === "Student" && form.get("admission") === "ADM-2401") { setNotice("Admission number ADM-2401 already belongs to Ayesha Khan."); return; } notify(kind === "Student" ? "Student saved and audit entry created" : "Payment saved — receipt NSP-2025-0916 is ready"); };
  const studentFields = [["Roll number", "roll", "06"], ["Admission number", "admission", "ADM-2409"], ["Full name", "name", ""], ["Father name", "father", ""], ["Mother name", "mother", ""], ["Date of birth", "dob", "", "date"], ["Guardian contact", "guardian", "0300 000 0000"], ["Contact number", "phone", "0300 000 0000"], ["Email", "email", ""], ["CNIC / B-form", "cnic", ""], ["Class", "class", "Grade 9", "select"], ["Section", "section", "A", "select"], ["Tuition fee", "tuition", "9,500"], ["Transport fee", "transport", "0"]];
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label={`Add ${kind}`}><form className="record-modal" onSubmit={submit}><header><div><p className="eyebrow">NEW RECORD</p><h2>{kind === "Student" ? "Enroll a student" : "Record a fee payment"}</h2><p>{kind === "Student" ? "Required identifiers are checked before enrollment." : "A receipt will be created after payment is saved."}</p></div><button type="button" className="modal-close" onClick={close}>×</button></header>{kind === "Student" ? <><div className="photo-drop"><i>＋</i><span><b>Student photo</b><small>PNG or JPG · optional</small></span><button type="button">Upload</button></div><div className="form-grid">{studentFields.map(([label,name,value,type]) => <label key={name}>{label}{type === "select" ? <select name={name}><option>{value}</option><option>Grade 8</option><option>Grade 7</option></select> : <input name={name} required={["roll","admission","name","father"].includes(name)} type={type || "text"} defaultValue={value} />}</label>)}</div><label className="form-area">Address<textarea placeholder="Residential address" /></label><div className="check-line"><input id="same" type="checkbox"/><label htmlFor="same">Guardian contact is the same as contact number</label><span>All changes are retained in history</span></div></> : <><div className="student-strip"><i>AK</i><span><b>Ayesha Khan</b><small>ADM-2401 · Grade 9-A</small></span><button type="button">Change student</button></div><div className="form-grid fee-form">{[["Billing month","month","September 2025"],["Tuition fee","tuition","9,500"],["Stationery fee","stationery","500"],["Transport fee","transport","0"],["Discount","discount","0"],["Late fee","late","0"],["Amount paid","paid","10,000"],["Payment date","date","", "date"],["Payment method","method","Cash","select"],["Received by","received","Sarah Ahmed"]].map(([label,name,value,type])=><label key={name}>{label}{type === "select"?<select><option>{value}</option><option>Cheque</option><option>Bank transfer</option><option>Online</option></select>:<input defaultValue={value} type={type||"text"}/>}</label>)}</div><label className="form-area">Remarks<textarea placeholder="Optional payment note" /></label></>}{notice && <p className="modal-error">! {notice}</p>}<footer><button type="button" className="cancel-button" onClick={close}>Cancel</button><button className="primary-button" type="submit">{kind === "Student" ? "Save student" : "Save & create receipt"}</button></footer></form></div>;
}

function SettingsPage({ toast }: { toast: (x: string) => void }) {
  const sections = [
    ["School", ["School information", "General preferences", "Academic sessions", "Custom fields"]],
    ["Finance", ["Fee settings", "Default class fees", "Receipt settings", "Donations"]],
    ["People & access", ["User accounts", "Permissions", "Startup screen", "Keyboard shortcuts"]],
    ["System", ["Messaging settings", "ID card settings", "Theme settings", "Backup settings", "Branding", "Card authentication"]],
  ];
  const [active, setActive] = useState("School information");
  const fieldGroups: Record<string, string[]> = { "School information": ["School name", "School address", "Phone number", "Official email"], "General preferences": ["Timezone", "Date format", "Default language", "Week starts on"], "Fee settings": ["Monthly due date", "Grace period (days)", "Default late fee", "Payment reminder cadence"], "Default class fees": ["Class", "Tuition fee", "Stationery fee", "Transport fee"], "User accounts": ["Account name", "Role", "Allowed sections", "Account status"], "Permissions": ["Role", "Students", "Finance", "Settings access"], "Receipt settings": ["Receipt prefix", "Thermal layout", "Footer policy", "Signature label"], "Theme settings": ["Interface appearance", "Accent color", "Compact table mode", "Reduce motion"], "Backup settings": ["Automatic daily backup", "Backup time", "Retention period", "Verify after backup"] };
  const fields = fieldGroups[active] || ["Primary setting", "Configuration", "Access level", "Status"];
  return <><section className="page-intro compact"><div><p className="eyebrow">SYSTEM CONFIGURATION</p><h1>Settings</h1><p>Control how Northstar works for your school, team, and families.</p></div><button className="primary-button" onClick={() => toast("Settings saved successfully")}>Save changes</button></section><section className="settings-shell"><aside className="settings-rail">{sections.map(([group, items]) => <section key={group}><p>{group}</p>{(items as string[]).map(item => <button key={item} className={active === item ? "selected" : ""} onClick={() => setActive(item)}>{item}<span>›</span></button>)}</section>)}</aside><div className="settings-content"><div className="settings-title"><div><p className="eyebrow">SETTINGS / {active.toUpperCase()}</p><h2>{active}</h2><span>{active === "School information" ? "The identity shown on receipts, reports, cards, and parent messages." : "Choose the defaults your team will use across the workspace."}</span></div><button className="subtle-button" onClick={() => toast(`${active} history opened`)}>◷ View history</button></div><div className="settings-tabs"><button className="on">General</button><button>Advanced</button><button>Audit history</button></div><section className="settings-panel"><div className="panel-heading"><div><h3>Configuration</h3><p>Changes are recorded in the activity history.</p></div><i>● Live</i></div><div className="setting-fields">{fields.map((field, index) => <label key={field}>{field}{index === 0 && active === "Theme settings" ? <select defaultValue="Light"><option>Light</option><option>Dark</option><option>System</option></select> : index === 3 && ["User accounts", "Permissions", "Backup settings"].includes(active) ? <span className="switch-line"><b>Enabled</b><button type="button" aria-label={`Toggle ${field}`} onClick={() => toast(`${field} toggled`)}><i></i></button></span> : <input defaultValue={index === 0 && active === "School information" ? "Northstar Public School" : index === 1 && active === "School information" ? "14 Garden Road, Lahore" : ""} placeholder={`Enter ${field.toLowerCase()}`} />}</label>)}</div></section><section className="audit-strip"><i>◌</i><span><b>Database connection</b><small>Connected securely · last verified just now</small></span><button onClick={() => toast("Connection verification started")}>Verify connection</button></section></div></section></>;
}

function ModulePage({ page, toast }: { page:string; toast:(x:string)=>void }) {
  const modules: Record<string, { description: string; tabs: string[]; headers: string[]; rows: string[][]; action: string }> = {
    "Families": { description: "Guardian records, household balances, and family payment history.", tabs: ["Families", "Guardians", "Payment history", "Emergency contacts"], headers: ["Family", "Primary guardian", "Students", "Combined balance", "Phone", "Status"], rows: [["Khan family", "Muhammad Khan", "Ayesha, Ibrahim", "Rs. 4,500", "0301 245 8092", "Active"], ["Noor family", "Irfan Noor", "Fatima", "Rs. 9,500", "0308 772 1045", "Attention"]], action: "Add family" },
    "Exams & results": { description: "Create assessments, enter marks, calculate results, and issue report cards.", tabs: ["Exam sessions", "Subjects", "Marks entry", "Results", "Report cards"], headers: ["Exam session", "Class", "Subjects", "Entries", "Published", "Status"], rows: [["Term 1 · 2025", "Grades 1–10", "26 subjects", "1,104 / 1,248", "Sep 30", "In progress"], ["Monthly test · Sep", "Grades 6–8", "14 subjects", "684 / 684", "Sep 16", "Published"]], action: "Create exam" },
    "Timetable": { description: "Coordinate class periods, teachers, rooms, and templates across the school week.", tabs: ["Class timetable", "Teacher timetable", "Subjects", "Periods", "Rooms", "Templates"], headers: ["Class", "Day", "Periods", "Room", "Class teacher", "Status"], rows: [["Grade 9-A", "Monday–Friday", "8 periods", "B-12", "Maryam Iqbal", "Published"], ["Grade 8-C", "Monday–Friday", "8 periods", "A-07", "Usman Arif", "Draft"]], action: "Add timetable entry" },
    "ID cards": { description: "Prepare front and back cards, placeholder templates, and print-ready student batches.", tabs: ["Card templates", "Front design", "Back design", "Placeholders", "Print queue"], headers: ["Template", "Card size", "Orientation", "Placeholders", "Last edited", "Status"], rows: [["2025 Student ID", "86 × 54 mm", "Landscape", "18 fields", "Today, 10:12", "Active"], ["Staff ID · Standard", "86 × 54 mm", "Landscape", "12 fields", "Sep 01", "Active"]], action: "New template" },
    "Analytics": { description: "Financial reporting from fees, donations, salaries, and operational expenses.", tabs: ["Profit / loss", "Yearly summary", "Fee trend", "Expense trend", "Salary trend"], headers: ["Period", "Fee income", "Donations", "Salaries", "Expenses", "Net balance"], rows: [["September 2025", "Rs. 842,000", "Rs. 48,000", "Rs. 384,000", "Rs. 96,400", "Rs. 409,600"], ["August 2025", "Rs. 811,000", "Rs. 20,000", "Rs. 376,000", "Rs. 88,900", "Rs. 366,100"]], action: "Export report" },
    "Transport": { description: "Manage routes, vehicles, drivers, stops, assignments, and transport-fee tracking.", tabs: ["Routes", "Vehicles", "Drivers", "Bus stops", "Student assignments", "Transport fees"], headers: ["Route", "Vehicle", "Driver", "Students", "Monthly fee", "Status"], rows: [["R-01 · Model Town", "LEA-4521", "Tariq Mehmood", "38", "Rs. 1,500", "Active"], ["R-02 · Gulberg", "LEB-8840", "Asif Raza", "31", "Rs. 1,800", "Active"]], action: "Create route" },
    "Reports": { description: "Generate filtered, printable, and export-ready reports across every school function.", tabs: ["All reports", "Academic", "Fees", "Finance", "Staff", "Attendance"], headers: ["Report", "Category", "Date range", "Last generated", "Format", "Actions"], rows: [["Monthly fee collection", "Fees", "September 2025", "Today, 09:45", "PDF / CSV", "Generate"], ["Class-wise income", "Finance", "September 2025", "Yesterday", "PDF / CSV", "Generate"]], action: "Generate report" },
    "Automation": { description: "Build monitored rules for reminders, alerts, receipts, defaulters, and backups.", tabs: ["Rules", "Execution log", "Templates"], headers: ["Rule name", "Condition", "Action", "Last executed", "Enabled", "Actions"], rows: [["Fee reminder · 7 days", "Fee unpaid for 7 days", "Send reminder", "Today, 08:00", "Enabled", "Edit"], ["Backup safeguard", "Backup overdue", "Display alert", "Yesterday, 04:30", "Enabled", "Edit"]], action: "Create rule" },
    "Backup": { description: "Encrypted snapshots, verification, recovery, and transparent backup history.", tabs: ["Overview", "Backup history", "Restore", "Automatic schedule"], headers: ["Backup date", "Size", "Storage", "Verification", "Notes", "Status"], rows: [["Sep 16, 2025 · 04:30", "428 MB", "Secure cloud", "Verified", "Daily automatic backup", "Complete"], ["Sep 15, 2025 · 04:30", "421 MB", "Secure cloud", "Verified", "Daily automatic backup", "Complete"]], action: "Create backup" },
    "Alerts": { description: "Resolve exceptions across fee collection, payroll, reminders, backups, and system health.", tabs: ["All alerts", "Fees", "Payroll", "System", "Resolved"], headers: ["Alert type", "Severity", "Related record", "Created", "Description", "Status"], rows: [["Overdue fee", "High", "74 student accounts", "Today, 08:12", "Fees unpaid for 10+ days", "Open"], ["Salary pending", "Medium", "September payroll", "Today, 07:00", "3 payments await approval", "Open"]], action: "Resolve selected" },
    "Activity logs": { description: "A complete audit trail of actions, changes, devices, and record history.", tabs: ["All activity", "Student records", "Finance", "System", "Failed actions"], headers: ["User", "Action", "Section", "Record", "Date & time", "Status"], rows: [["Sarah Ahmed", "Updated payment", "Fees", "REC-24091", "Today, 10:22", "Success"], ["Ali Hassan", "Created student", "Students", "ADM-2409", "Today, 09:42", "Success"]], action: "Export log" },
    "Dynamic information": { description: "Search any operational record and inspect its raw fields, linked records, photo, and history.", tabs: ["Students", "Staff", "Fees", "Expenses", "Donations"], headers: ["Entity", "Record ID", "Name / detail", "Last updated", "Owner", "Status"], rows: [["Student", "ADM-2401", "Ayesha Khan", "Today, 10:22", "Sarah Ahmed", "Active"], ["Fee payment", "REC-24091", "September · Ayesha Khan", "Today, 09:42", "Sarah Ahmed", "Active"]], action: "Inspect record" },
    "Monthly fee & salary status": { description: "Track payments across months and open paid or unpaid details without leaving the workflow.", tabs: ["Fee tracker", "Salary tracker", "Paid details", "Unpaid details"], headers: ["Person", "January", "February", "March", "April", "Overall status"], rows: [["Ayesha Khan", "Paid", "Paid", "Paid", "Pending", "Partially paid"], ["Maryam Iqbal", "Paid", "Paid", "Paid", "Paid", "Paid"]], action: "Export status" },
    "Developer info": { description: "Read-only application, build, support, and system-identity information.", tabs: ["Application", "Build", "Support", "System identity"], headers: ["Property", "Value", "Updated", "Access", "Notes", "Status"], rows: [["Application edition", "Northstar Web", "Today", "Read only", "School management portal", "Active"], ["Build version", "1.0.0", "Today", "Read only", "Production-ready UI", "Active"]], action: "Copy system report" },
    "Trash bin": { description: "Review archived records, inspect original data context, and restore only when permissions allow.", tabs: ["All archived", "Students", "Finance", "Staff", "Restore history"], headers: ["Module", "Record ID", "Record", "Archived by", "Archived date", "Status"], rows: [["Students", "ADM-2281", "Kashif Ahmed", "Sarah Ahmed", "Sep 14, 2025", "Archived"], ["Expenses", "EXP-1028", "Old maintenance entry", "Ali Hassan", "Sep 11, 2025", "Archived"]], action: "Restore selected" },
    "Historical records": { description: "Browse prior sessions, locked periods, versions, and approved recovery or export actions.", tabs: ["Sessions", "Archived periods", "Versions", "Exports"], headers: ["Period", "Module", "Records", "Locked", "Last change", "Status"], rows: [["2024–25", "Academic session", "1,109", "Yes", "Jun 30, 2025", "Archived"], ["August 2025", "Finance", "386", "Yes", "Sep 01, 2025", "Archived"]], action: "Export history" },
  };
  const aliases: Record<string, string> = { "Family management": "Families", "Financial analytics": "Analytics", "Monthly fee & salary status": "Monthly fee & salary status", "Dynamic information": "Dynamic information", "Developer info": "Developer info", "Trash bin": "Trash bin", "Historical records": "Historical records" };
  const module = modules[aliases[page] || page] || { description: "Operational tools for your school.", tabs: ["Overview"], headers: ["Record", "Status"], rows: [["No records", "Ready"]], action: "Create new" };
  const [tab, setTab] = useState(module.tabs[0]);
  return <><section className="page-intro compact"><div><p className="eyebrow">NORTHSTAR / OPERATIONS</p><h1>{page}</h1><p>{module.description}</p></div><div className="intro-actions"><button className="subtle-button" onClick={() => toast("Export prepared for download")}>⇩ Export</button><button className="primary-button" onClick={() => toast(`${module.action} workspace opened`)}>＋ {module.action}</button></div></section><section className="module-tabs">{module.tabs.map(item => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</section><section className="module-toolbar"><label>⌕ <input placeholder={`Search ${tab.toLowerCase()}…`} /></label><select><option>All statuses</option><option>Active</option><option>Pending</option></select><select><option>September 2025</option><option>August 2025</option></select><button onClick={() => toast("Filter options reset")}>↻ Reset filters</button></section><section className="module-data"><div className="module-data-head"><div><b>{tab}</b><small>{module.rows.length} visible records · sorted by latest activity</small></div><button onClick={() => toast("Print preview opened")}>▤ Print</button></div><div className="table-scroll"><table><thead><tr><th><input aria-label="Select all records" type="checkbox"/></th>{module.headers.map(h => <th key={h}>{h} <small>↕</small></th>)}</tr></thead><tbody>{module.rows.map((row,index) => <tr key={index}><td><input aria-label={`Select ${row[0]}`} type="checkbox"/></td>{row.map((value, cell) => <td key={cell}>{["Active", "Published", "Enabled", "Complete", "Success"].includes(value) ? <span className="status active">{value}</span> : ["Attention", "In progress", "Draft", "Open", "Medium", "High"].includes(value) ? <span className="status pending">{value}</span> : value}</td>)}</tr>)}</tbody></table></div><footer className="pagination"><span>Showing <b>1–{module.rows.length}</b> of <b>{module.rows.length}</b></span><div><button disabled>←</button><button className="current">1</button><button>→</button></div></footer></section></>;
}
